"""
Water Potability TFLite — Python Test Server
=============================================
Serves the web UI and exposes a /predict endpoint
that runs inference on the TFLite model.

Requirements:
    pip install flask numpy

Files needed in the same directory:
    water_potability_model.tflite   (generated by water_potability_model_v2_tflite.py)
    templates/index.html            (the web UI)

Run:
    python server.py
    → Open http://localhost:5000
"""

import os
import json
import numpy as np
from flask import Flask, request, jsonify, render_template

# ── TFLite interpreter (use tflite-runtime if available, else full TF) ────────
try:
    import tflite_runtime.interpreter as tflite
    Interpreter = tflite.Interpreter
    print("✅  Using tflite_runtime")
except ImportError:
    import tensorflow as tf
    Interpreter = tf.lite.Interpreter
    print("✅  Using tensorflow.lite.Interpreter")

# ── RobustScaler params (hardcoded from training — no sklearn needed at serve) ─
# These values come from the scaler fitted on the 4-feature dataset.
# Update them if you retrain the model.
SCALER_CENTER = np.array([7.036752, 3.954964, 6.964399, 20927.830])  # median per feature
SCALER_SCALE  = np.array([1.523814, 0.787856, 1.582651, 11666.070])  # IQR per feature

FEATURE_NAMES = ["ph", "Turbidity", "Chloramines", "Solids"]
MODEL_PATH    = "water_potability_model.tflite"

# ── Load interpreter once at startup ─────────────────────────────────────────
if not os.path.exists(MODEL_PATH):
    raise FileNotFoundError(
        f"Model not found: {MODEL_PATH}\n"
        "Run water_potability_model_v2_tflite.py first to generate it."
    )

interpreter = Interpreter(model_path=MODEL_PATH)
interpreter.allocate_tensors()
INP_IDX = interpreter.get_input_details()[0]["index"]
OUT_IDX = interpreter.get_output_details()[0]["index"]
print(f"✅  Model loaded: {MODEL_PATH}")

app = Flask(__name__)


def preprocess(values: list) -> np.ndarray:
    """Apply RobustScaler: scaled = (x - center) / scale"""
    x = np.array(values, dtype=np.float32)
    return ((x - SCALER_CENTER) / SCALER_SCALE).reshape(1, -1).astype(np.float32)


def predict_safety(values: list) -> dict:
    """Run TFLite inference and return safety score + label."""
    x = preprocess(values)
    interpreter.set_tensor(INP_IDX, x)
    interpreter.invoke()
    raw = float(interpreter.get_tensor(OUT_IDX).flatten()[0])
    score = float(np.clip(raw, 0.0, 1.0))
    pct   = round(score * 100, 1)

    if score >= 0.6:
        label, status = "POTABLE", "safe"
    elif score >= 0.3:
        label, status = "WARNING", "warning"
    else:
        label, status = "NOT POTABLE", "danger"

    return {"score": score, "percentage": pct, "label": label, "status": status}


# ── Routes ────────────────────────────────────────────────────────────────────
@app.route("/")
def index():
    return render_template("index.html")


@app.route("/predict", methods=["POST"])
def predict():
    try:
        data = request.get_json()

        ph          = float(data["ph"])
        turbidity   = float(data["turbidity"])
        chloramines = float(data["chloramines"])
        solids      = float(data["solids"])

        # Validate ranges
        errors = []
        if not (0 <= ph <= 14):
            errors.append("pH must be 0–14")
        if not (0 <= turbidity <= 10):
            errors.append("Turbidity must be 0–10 NTU")
        if not (0 <= chloramines <= 15):
            errors.append("Chloramines must be 0–15 mg/L")
        if not (0 <= solids <= 70000):
            errors.append("Solids must be 0–70,000 mg/L")
        if errors:
            return jsonify({"error": "; ".join(errors)}), 400

        result = predict_safety([ph, turbidity, chloramines, solids])
        return jsonify(result)

    except (KeyError, ValueError, TypeError) as e:
        return jsonify({"error": f"Invalid input: {str(e)}"}), 400


@app.route("/test-cases", methods=["GET"])
def test_cases():
    """Run the 3 standard test cases and return results."""
    cases = [
        {"label": "POTABLE",      "input": [7.37, 3.21, 5.94,  9460.0]},
        {"label": "WARNING",      "input": [7.08, 3.96, 7.12, 22014.0]},
        {"label": "NOT POTABLE",  "input": [3.71, 4.50, 6.63, 18630.0]},
        {"label": "QUICK TEST",   "input": [7.4,  3.5,  5.9,   9000.0]},
    ]
    results = []
    for case in cases:
        r = predict_safety(case["input"])
        results.append({
            "expected": case["label"],
            "input": dict(zip(FEATURE_NAMES, case["input"])),
            **r
        })
    return jsonify(results)


if __name__ == "__main__":
    print("\n" + "─"*50)
    print("  💧 Water Potability Test Server")
    print("─"*50)
    print("  UI  → http://localhost:5000")
    print("  API → POST http://localhost:5000/predict")
    print("        GET  http://localhost:5000/test-cases")
    print("─"*50 + "\n")
    app.run(debug=True, host="0.0.0.0", port=5000)
